name: Generate PlantUML Diagrams

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [closed]
  
  # Allow manual triggering
  workflow_dispatch:

# Add permissions block
permissions:
  contents: write

jobs:
  generate-diagrams:
    name: Generate Class Diagrams
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper analysis

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install PlantUML
        run: |
          sudo apt-get update
          sudo apt-get install -y plantuml
          plantuml -version

      - name: Install Kodify CLI
        run: |
          dotnet tool install --global Kodify.CLI --version 0.0.1-dev-0006 || dotnet tool update --global Kodify.CLI --version 0.0.1-dev-0006

      - name: Generate PUML Diagrams
        run: |
          mkdir -p diagrams
          which kodify
          kodify puml --output ./diagrams
          
      - name: Verify Diagrams Generated
        run: |
          if [ ! -f "./diagrams/ClassDiagrams.puml" ]; then
            echo "Error: PUML diagrams were not generated!"
            exit 1
          fi

      - name: Generate PNG from PUML
        run: |
          cd diagrams
          for file in *.puml; do
            plantuml "$file"
          done

      - name: Verify PNG Generated
        run: |
          if [ ! -f "./diagrams/ClassDiagrams.png" ]; then
            echo "Error: PNG diagrams were not generated!"
            exit 1
          fi

      - name: Commit and Push Changes
        run: | 
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add diagrams/*
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update class diagrams [skip ci]" && git push)